### ISSUE TITLE
getOne query

### ISSUE THREAD

**Issue by xor83** [verkhoumov/codeigniter-mongodb-library1#37]
Hi,

$this->mongo_db->where(['user_email' => $username, 'user_password' => $password])
					->getOne('col_users');

The above query returns document under zeroth key. How can i get data without [0] key?

**Comment by daravichit** [comment]
$info = $this->mongo_db->where(['user_email' => $username, 'user_password' => $password])
->getOne('col_users');
$info = $this->mongo_db->row_array($info);

**Comment by xor83** [comment]
thanks
