### ISSUE TITLE
How use List indexes?

### ISSUE THREAD

**Issue by ThienTranDuy** [verkhoumov/codeigniter-mongodb-library1#39]
/**
     * 	--------------------------------------------------------------------------------
     * 	List indexes
     * 	--------------------------------------------------------------------------------
     *
     * 	Lists all indexes in a collection.
     *
     * 	@usage : $this->mongo_db->list_indexes($collection);
     */
    public function list_indexes($collection = "") {
        if (empty($collection)) {
            show_error("No Mongo collection specified to remove all indexes from", 500);
        }

        return ($this->db->{$collection}->getIndexInfo());
    }

How can I do it in this version?

**Comment by hao159** [comment]
Hi guy,

Give to u simple method check and create index. hope this helps 👍 

`
/**
     *     --------------------------------------------------------------------------------
     *     //! Add indexes
     *     --------------------------------------------------------------------------------
     *
     *     Ensure an index of the keys in a collection with optional parameters. To set values to descending order,
     *     you must pass values of either -1, FALSE, 'desc', or 'DESC', else they will be
     *     set to 1 (ASC).
     *
     *     @usage : $this->mongo_db->add_index($collection, array('first_name' => 'ASC', 'last_name' => -1), array('unique' => TRUE));
     */

    public function add_index($collection = "", $keys = array(), $options = array())
    {
        if (empty($collection)) {
            show_error("No Mongo collection specified to add index to", 500);
        }

        if (empty($keys) || !is_array($keys)) {
            show_error("Index could not be created to MongoDB Collection because no keys were specified", 500);
        }

        $indexes = array();
        foreach ($keys as $key => $val) {
            if ($val == -1 || $val === false || strtolower($val) == 'desc') {
                $index = array(
                    'name' => $key . '_1',
                    'key' => array(
                        $key => -1,
                    ),
                );
            } else {
                $index = array(
                    'name' => $key . '_1',
                    'key' => array(
                        $key => 1,
                    ),
                );
            }
            $indexes[] = $index;
        }
        $command = [
            'createIndexes' => $collection,
            'indexes' => $indexes,
        ];

        if ($this->_command($command, __METHOD__)) {
            $this->_clear();
            return ($this);
        } else {
            show_error("An error occured when trying to add an index to MongoDB Collection", 500);
        }
    }
    /**
     *     --------------------------------------------------------------------------------
     *     List indexes
     *     --------------------------------------------------------------------------------
     *
     *     Lists all indexes in a collection.
     *
     *     @usage : $this->mongo_db->list_indexes($collection);
     */

    public function list_indexes($collection = "")
    {
        if (empty($collection)) {
            show_error("No Mongo collection specified to remove all indexes from", 500);
        }
        $command = [
            'listIndexes' => $collection,
        ];

        return $this->_command($command, __METHOD__);

    }

    /**
     *     --------------------------------------------------------------------------------
     *     _clear
     *     --------------------------------------------------------------------------------
     *
     *     Resets the class variables to default settings
     */
    private function _clear()
    {
        $this->selects = array();
        $this->updates = array();
        $this->wheres = array();
        $this->groups = array();
        $this->limit = 999999;
        $this->offset = 0;
        $this->sorts = array();
    }`

**Comment by ThienTranDuy** [comment]
> Hi guy,
> 
> Give to u simple method check and create index. hope this helps 👍
> 
> `
> /**
> * --------------------------------------------------------------------------------
> * //! Add indexes
> * --------------------------------------------------------------------------------
> *
> * Ensure an index of the keys in a collection with optional parameters. To set values to descending order,
> * you must pass values of either -1, FALSE, 'desc', or 'DESC', else they will be
> * set to 1 (ASC).
> *
> * @Usage : $this->mongo_db->add_index($collection, array('first_name' => 'ASC', 'last_name' => -1), array('unique' => TRUE));
> */
> 
> ```
> public function add_index($collection = "", $keys = array(), $options = array())
> {
>     if (empty($collection)) {
>         show_error("No Mongo collection specified to add index to", 500);
>     }
> 
>     if (empty($keys) || !is_array($keys)) {
>         show_error("Index could not be created to MongoDB Collection because no keys were specified", 500);
>     }
> 
>     $indexes = array();
>     foreach ($keys as $key => $val) {
>         if ($val == -1 || $val === false || strtolower($val) == 'desc') {
>             $index = array(
>                 'name' => $key . '_1',
>                 'key' => array(
>                     $key => -1,
>                 ),
>             );
>         } else {
>             $index = array(
>                 'name' => $key . '_1',
>                 'key' => array(
>                     $key => 1,
>                 ),
>             );
>         }
>         $indexes[] = $index;
>     }
>     $command = [
>         'createIndexes' => $collection,
>         'indexes' => $indexes,
>     ];
> 
>     if ($this->_command($command, __METHOD__)) {
>         $this->_clear();
>         return ($this);
>     } else {
>         show_error("An error occured when trying to add an index to MongoDB Collection", 500);
>     }
> }
> /**
>  *     --------------------------------------------------------------------------------
>  *     List indexes
>  *     --------------------------------------------------------------------------------
>  *
>  *     Lists all indexes in a collection.
>  *
>  *     @usage : $this->mongo_db->list_indexes($collection);
>  */
> 
> public function list_indexes($collection = "")
> {
>     if (empty($collection)) {
>         show_error("No Mongo collection specified to remove all indexes from", 500);
>     }
>     $command = [
>         'listIndexes' => $collection,
>     ];
> 
>     return $this->_command($command, __METHOD__);
> 
> }
> 
> /**
>  *     --------------------------------------------------------------------------------
>  *     _clear
>  *     --------------------------------------------------------------------------------
>  *
>  *     Resets the class variables to default settings
>  */
> private function _clear()
> {
>     $this->selects = array();
>     $this->updates = array();
>     $this->wheres = array();
>     $this->groups = array();
>     $this->limit = 999999;
>     $this->offset = 0;
>     $this->sorts = array();
> }`
> ```

Thank you Hao. It helpful for me
